name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      run: echo "Code checkout done"

    - name: Build Docker image
      id: build_image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: image-front-interface:latest
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
      env:
        DOCKER_BUILDKIT: 1
        DOCKER_CLI_EXPERIMENTAL: enabled
      run: echo "Docker build and push done"