name: Integration Continue

on: 
  push: 
    branches: 
    - main 
  pull_request: 
    branches: 
    - main
    
jobs:
  buil:
    runs-on: ubuntu-latest
    steps:
    - name: Test git action 
      run: echo "Je ne fais rien je suis seulement un test pour git action."
    - name: Test git action 2 
      run: echo "rien juste test."
    - name: Test git action 3
      run: echo "Toujours rien."
      